spring: 
 application:
  name: user-service
 data:
  mongodb:
    host: localhost
    port: 27017
    database: live_poll
server:
 port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka