spring: 
  application: 
    name: api-gateway
  cloud: 
    discovery: 
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: user-communication-service
          uri: lb://user-communication-service
          predicates:
            - Path=/ws/** 

        - id: user-services
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        
