spring: 
  application: 
    name: api-gateway
  cloud: 
    discovery: 
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: testing_route
          uri: https://google.co.in
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory

        - id: user_communication_service
          uri: http://localhost:8854
          predicates:
            - Path=/ws/** 

        - id: user-services
          uri: http://localhost:9001
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        
