server:
 port: 8850
spring :
 application:
  name: auth-service
 data:
  mongodb:
   host: localhost
   port: 27017
   database: live_poll
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
